name: PlantsMonitor
description: "Plants Monitor app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.6
  http: ^1.2.0
  provider: ^6.0.1
  path_provider: ^2.1.4
  archive: ^3.6.1
  flutter_downloader: ^1.11.7
  flutter_file_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
